services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: x3akqrtww
      POSTGRES_USER: postgres
      POSTGRES_DB: blog


  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080